### PR TITLE
Best merge

### PR DESCRIPTION
**Pull request by rustyconover**
Hi Pedro,

Here is a big merge.  I'm prepared to start merging or communicating more, but I'm also prepared to fork this module as we've been talking about it for a while but never seem to get anywhere.

My goals would be improve support and performance by allowing data and lists to be passed by reference, better parameter type checking by using Kavorka, allow the use of Futures to allow parallel uploads and downloads.  Ideally it would be a fine time to break the API up, and either go with full Moose like the Client does, or make a lighter API using Moo.

You can see some of the use of Futures in Amazon::DynamoDB.

Thanks,

Rusty

### CODE REVIEW

**Comment by pnu** [comment]
Yes, please! Would you Rusty consider taking CPAN co-maint of this project? Is there something I can help with? I think the last year shows that @pfig is not committed to maintain this module.

**Comment by rustyconover** [comment]
@pnu @renatocron: I've emailed @pfig and modules@perl.org again to request co-maintainership.  Lets give them some time to see if they reply, if by April 15th nothing happens we could push forward with a fork.

**Comment by renatocron** [comment]
Thank you!


<http://www.eokoe.com>

Renato Santos
renato.santos@eokoe.com <+henry@eokoe.com>
(11) 3386-8181
www.eokoe.com
b-cam.com.br

**Comment by TJC** [comment]
I can't believe this pull request has been here for ten months! Just fork it already! :)

**Comment by rustyconover** [comment]
I'm happy to announce I now have co-maintainership of Net::Amazon::S3 from modules@perl.org, so expect a release out of my fork shortly.

**Comment by renatocron** [comment]
Great news!

**Comment by kizashi1122** [comment]
:+1:

**Comment by jrc-imente** [comment]
Perfect!

On Tue, Mar 31, 2015 at 8:44 AM, Kizashi Nagata <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pfig/net-amazon-s3/pull/47#issuecomment-87965200>.
>



-- 
*Josep Roura*
Developer


Tél. : +34 972 982 964

*www.augure.com* <http://www.augure.com/> | *Blog.* Reputation in action
<http://blog.augure.es/> | *Twitter. *@AugureSpain
<https://twitter.com/AugureSpain>
*Skype *: josep.roura | *Access map.* Augure Girona
<https://maps.google.com/maps?q=Eiximenis+12,+17001+Girona,+Espanya&hl=ca&sll=50.956548,6.799948&sspn=30.199963,86.044922&hnear=Carrer+Eiximenis,+12,+17001+Girona,+Espanya&t=m&z=16>

**Comment by ranguard** [comment]
@rustyconover Wonderful news that you are taking on co-maintainership

**Comment by pfig** [comment]
Hey @rustyconover,

I finally got some head space for this, and just saw your pull request, and I can only say thank you so much. I've tried to contact Léon, from time to time, but have failed to be on IRC at the same time as himself, so I wasn't able to add you as a co-maintainer before (as I'm co-maint myself) - admittedly I could've emailed him, but I didn't.

Apologies to all for my lack of responsiveness in the past 12 months or so :\

**Comment by rustyconover** [comment]
Hey @pfig,

So glad to hear from you.  How do you want to proceed?  Do you want to cherry pick out of this merge request, or should we just use my tree?

Rusty

**Comment by rustyconover** [comment]
Closing, as released 0.80 to CPAN with this merge.

**Pull request closed without merging**
